apiVersion: v1
kind: Service
metadata:
  name: wazuh-workers
  labels:
    app: wazuh-manager
  annotations:
    {{ .Values.annotations.worker_svc }}
spec:
  type: LoadBalancer
  selector:
    app: wazuh-manager
    node-type: worker
  ports:
    - name: agent-events
      port: 1514
      targetPort: 1514
    - name: syslog-listener
      port: 514
      targetPort: 514
