apiVersion: v1
kind: Service
metadata:
  name: wazuh
  labels:
    app: wazuh-manager
  annotations:
    {{ .Values.annotations.manager_svc }}
spec:
  type: LoadBalancer
  selector:
    app: wazuh-manager
    node-type: master
  ports:
    - name: registration
      port: 1515
      targetPort: 1515
    - name: api
      port: 55000
      targetPort: 55000
