apiVersion: v1
kind: Secret
metadata:
    name: indexer-cred

data:
{{- $secret := lookup "v1" "Secret" .Release.Namespace "indexer-cred" -}}

{{ if $secret -}}
  username: {{ $secret.data.username }}
  password: {{ $secret.data.password }}

{{ else if .Values.secrets.indexer -}}
  username: {{ .Values.secrets.indexer.username | b64enc | quote }}
  password: {{ .Values.secrets.indexer.password | b64enc | quote }}

{{ end }}
