apiVersion: v1
kind: Secret
metadata:
    name: indexer-cred

{{ $secret := lookup "v1" "Secret" .Release.Namespace "indexer-cred" -}}
{{- if $secret -}}
data:
  username: {{ $secret.data.username }}
  password: {{ $secret.data.password }}

{{- else if .Values.secrets.indexer -}}
data:
  username: {{ .Values.secrets.indexer.username | b64enc | quote }}
  password: {{ .Values.secrets.indexer.password | b64enc | quote }}

{{- end }}
