apiVersion: v1
kind: Secret
metadata:
  name: wazuh-cluster-key
type: Opaque

data:
{{ $secret := lookup "v1" "Secret" .Release.Namespace "wazuh-cluster-key" }}

{{- if $secret }}
  key: {{ $secret.data.cluster_key }}

{{- else if .Values.secrets.cluster_key }}
  key: {{ .Values.secrets.cluster_key }}

{{- else }}
  key: {{ randAlphaNum 32 | b64enc | quote }}

{{- end }}
