apiVersion: v1
kind: Secret
metadata:
  name: wazuh-api-cred

{{ $secret := lookup "v1" "Secret" .Release.Namespace "wazuh-api-cred" }}

{{- if $secret -}}
data:
  username: {{ $secret.data.username }}
  password: {{ $secret.data.password }}

{{- else if .Values.secrets.dashboard -}}
data:
  username: {{ .Values.secrets.api_cred.username | b64enc | quote }}
  password: {{ .Values.secrets.api_cred.password | b64enc | quote }}

{{- end }}
