apiVersion: v1
kind: Secret
metadata:
    name: wazuh-authd-pass

data:
{{- $secret := lookup "v1" "Secret" .Release.Namespace "wazuh-authd-pass" -}}

{{ if $secret -}}
  authd.pass: {{ $secret.data.authd.pass }}

{{ else if .Values.secrets.cluster_key -}}
  authd.pass: {{ .Values.secrets.authd }}

{{ else -}}
  authd.pass: {{ randAlphaNum 32 | b64enc | quote }}

{{ end }}
